# Generated by Django 5.2.5 on 2025-08-07 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionCenter',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.base')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('url', models.URLField(unique=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, editable=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('slug', models.SlugField(null=True)),
            ],
            bases=('hub.base',),
        ),
    ]
