# Generated by Django 5.2.4 on 2025-08-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncenter',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='distributioncenter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='distributioncenter',
            name='status',
            field=models.BooleanField(default=False, editable=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='distributioncenter',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Website URL'),
        ),
    ]
